openapi: 3.0.1
info:
  title: monster-gibbering-mouther
  x-cortex-tag: monster-gibbering-mouther
  x-cortex-custom-metadata:
    alignment: neutral-evil
    type: elemental
    challenge_rating: 23
    legendary: false
    armor_class: 12
    hit_points: 291
    source: dnd-5e
  x-cortex-type: monster
  x-cortex-git:
    github:
      repository: xycia-cortex/monster-gibbering-mouther
      alias: github-token-test
